# Generated by Django 3.1.6 on 2021-02-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20210210_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paymentdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
